### ISSUE TITLE
USER STORY: Navigation (SP: Est.)

### ISSUE THREAD

**Issue by Wouter-IT** [Wouter-IT/rate-it-def#15]
As a **user** I can **conveniently navigate the website through the navigation bar** so that **easily switch between pages and interact with the community**.

### Acceptance criteria
- 
-

## Tasks
- [ ] Logo linking to home page (SP Est.)
- [ ] Navigation menu (SP Est.)
- [ ] Nav dropdown for mobile
- [ ] Notifications
